application: gladiatus-helper
version: 1
runtime: python
api_version: 1

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /gm
  static_dir: gm

- url: /.*
  script: org/ddth/game/gladiatus/GladiatusHelper.py
