application: gladiatus-helper
version: 1
runtime: python
api_version: 1

handlers:

- url: /css
  static_dir: html/css

- url: /js
  static_dir: html/js
  
- url: /images
  static_dir: html/images
  
- url: /gm
  static_dir: gm

- url: /.*
  script: org/ddth/game/gladiatus/GladiatusHelper.py
